Feature/file export
xyng/yuoshi-studip-plugin pull request #18
Opened 2020-09-07 08:36 UTC by juliandierker

Danke @SmokyZone

2020-09-08 20:46 UTC, xyng requested changes
Ein paar Sachen habe ich noch gefunden. Rest scheint auf den ersten Blick ok

2020-09-08 20:46 UTC, xyng commented on app/pages/Packages/ImportPackage.tsx
> +            if (json === null) {
Hier vergesst ihr auf undefined zu prüfen, weshalb ihr später den Type-Cast braucht.
Alternative: bei useState einen Type angeben

2020-09-08 20:46 UTC, xyng commented on app/pages/Packages/ImportPackage.tsx
> +            console.log(url.href)
Das muss weg.

2020-09-08 20:46 UTC, xyng commented on app/pages/Packages/ImportPackage.tsx
> +            let xhr = new XMLHttpRequest()
Hier ist gefühlt ein fetch passender, weil ihr da direkt promises bekommt.
Mit Formdata sollte das umgehen können, das einzige, das man verliert, sind Up- und Download Progress Events.
(Disclaimer: vielleicht vertue ich mich und xhr ist in diesem Fall doch noch sinnvoller)

2020-09-08 20:46 UTC, xyng commented on app/pages/Packages/ImportPackage.tsx
> +            let blob = new Blob([JSON.stringify(newJson)], {
Warum let? Das kann ein const sein, und sollte es dann auch :-)

2020-09-08 20:46 UTC, xyng commented on app/pages/Packages/ImportPackage.tsx
> +            let formData = new FormData()
Warum let? Das kann ein const sein, und sollte es dann auch :-)

2020-09-08 20:46 UTC, xyng commented on app/pages/Packages/ImportPackage.tsx
> +                onChange={function (e: any) {
Funktionen bitte immer durch useCallback memoisieren

2020-09-08 20:46 UTC, xyng commented on app/pages/Tasks/Tasks.tsx
> +                onClick={() => {
Funktionen bitte immer durch useCallback memoisieren.
Vor allem derart lange Oschis sollten nicht inline vorkommen

2020-10-14 18:59 UTC, xyng requested changes
Ich habe noch Verbesserungsvorschläge finden können. Bei Fragen: gerne Kommentieren oder Slacken :-)
Insgesamt soll das euch helfen, bessere Komponenten mit saubererem Code zu bauen

2020-10-14 18:59 UTC, xyng commented on app/pages/Packages/ImportPackage.tsx
> +            let json = JSON.parse(event.target.result)
Wenn ihr beim State bleibt: Zwischenspeichern in Variable nicht nötig. Einfach setJson(JSON.parse(...))

2020-10-14 18:59 UTC, xyng commented on app/pages/Packages/ImportPackage.tsx
> +            const newJson: any = json
newJson weg (und die beiden folgenden Zeilen auch)

2020-10-14 18:59 UTC, xyng commented on app/pages/Packages/ImportPackage.tsx
> +            const blob = new Blob([JSON.stringify(newJson)], {
So könnt ihr das `newJson` Objekt mit any-Type vermeiden.

```suggestion
            const blob = new Blob([JSON.stringify({
                package: {
                    title: values.title,
                    slug: values.slug
                } 
            })], {
```

2020-10-14 18:59 UTC, xyng commented on app/pages/Packages/ImportPackage.tsx
> +            fetch(url.href, {
await auch für fetch benutzen (etwa so:)

```ts
try {
    const res = await fetch(...)
} catch (e) {
    // handle error
}

if (res.status >= 400) {
   // handle server-error
}

// wenn response-body benötigt wird
// await res.json() // oder .text() wenn es plaintext-inhalt ist

await reloadPackages()
```

2020-10-14 18:59 UTC, xyng commented on app/pages/Packages/ImportPackage.tsx
> +    const onChange = useCallback(async (event) => {
ggf. statt dem Change-Callback über `useRef` die Referenz auf das `input`-Element holen und die Selektierte Datei bei Submit auslesen.
Dadurch muss nicht auf jeden Change reagiert und die Daten nicht im State der Komponente gespeichert werden.

Beispiel:
```tsx
const inputRef = useRef<HTMLInputElement|null>(null)
// const onChange = ... löschen

const onSubmit = useCallback(async () => {
    // für refs braucht ihr keine dependency im zweiten Parameter von useCallback anzugeben.
    const input = inputRef.current

    if (!input || input.files.length === 0) {
        return;
    }

    const json = await new Promise(res => {
        const reader = new FileReader()
        reader.onload = (event) => res(event.target.result)
        reader.readAsText(input.files[0])
    })

    // request-kram aus dem bisherigen onSubmit
}, [])

return (
<>
    ...
    <input ref={inputRef}  ... />
    <PackageForm onSubmit={onSubmit} />
</>
)
```

2020-10-14 18:59 UTC, xyng commented on src/Api/Controller/PackagesController.php
> +    }
Hier ist whitespace, wo kein whitespace sein sollte :-)

2020-10-21 08:31 UTC, juliandierker commented on app/pages/Packages/ImportPackage.tsx
> +            let json = JSON.parse(event.target.result)
✔️

2020-10-21 08:53 UTC, juliandierker commented on app/pages/Packages/ImportPackage.tsx
> +            const blob = new Blob([JSON.stringify(newJson)], {
Wir haben uns jetzt drauf geeinigt, hier doch einen any type zu nutzen (irgendwie übersichtlicher), haben jedoch `newJson` vor `const blob...` verschoben

2020-10-21 09:10 UTC, juliandierker commented on app/pages/Packages/ImportPackage.tsx
> +            const newJson: any = json
s.o

2020-10-21 09:10 UTC, juliandierker commented on app/pages/Packages/ImportPackage.tsx
> +            fetch(url.href, {
✔️

2020-10-21 09:32 UTC, juliandierker commented on app/pages/Packages/ImportPackage.tsx
> +    const onChange = useCallback(async (event) => {
Typescript wirft leider Fehler - ich mache hieraus einen extra issue -> übernehmen erstmal onChange

2020-10-21 09:39 UTC, juliandierker commented on src/Api/Controller/PackagesController.php
> +    }
Wir versuchen es beim pushen "wegzulinten"

2020-10-22 07:16 UTC, xyng approved these changes

2020-10-22 07:16 UTC, xyng commented
Ok, dann soll das erstmal so passen!

2020-11-09 08:06 UTC, merged