Chore/usability
xyng/yuoshi-studip-plugin pull request #19
Opened 2020-09-08 08:56 UTC by SmokyZone

## Usability Änderungen:
### 1. Pakete Aufgaben bearbeiten

   - Routing zu "Metadaten bearbeiten" und "Aufgaben bearbeiten" umgedreght

### 2. Aufgaben: Metadaten Bearbeiten

   - Um die Metadaten einer Aufgabe zu bearbeiten muss man jetzt auf den Namen der Aufgabe klicken
   - Ist damit konsistent mit den Paketen

### 3. Unterscheidung - Umfrage, Multiple Choice

   - Umfragen haben jetzt ein eigenes Edit Menü.
   - Einige Checkboxen wurden entfernt, da sie nicht wirklich Sinn gemacht haben

### 4. Wirklich löschen?

   - Beim Löschen von Inhalten (Paketen, Aufgaben, etc. ) wird abgefragt, ob es wirklich gelöscht werden soll.

### 5. Redirect beim Speichern
   - Beim Erstellen eines Paketes wird man direkt zur Aufgabenliste des Paketes weitergeleitet
   - Beim Erstellen einer Aufgabe wird man direkt zur Edit-Seite der Aufgabe weitergeleitet

2020-09-08 20:51 UTC, xyng requested changes
Erster Aufschlag an Dingen, die mir auffallen

2020-09-08 20:51 UTC, xyng commented on app/pages/Packages/CreatePackage.tsx
> +const CreatePackage: React.FC<RouteComponentProps> = (props) => {
Hier direkt navigate raus-destructuren:
{ navigate }

2020-09-08 20:51 UTC, xyng commented on app/pages/Packages/CreatePackage.tsx
> +            if (props !== undefined && props.navigate !== undefined) {
Und dann hier navigate direkt benutzen:
navigate && navigate(...)

2020-09-08 20:51 UTC, xyng commented on app/pages/Packages/Packages.tsx
> +                window.confirm(
window.confirm ist nicht die feine englische (da blocking), aber fürs erste besser als nix 👍🏻

2020-09-08 20:51 UTC, xyng commented on app/pages/Task/CreateTask.tsx
> +const CreateTask: React.FC<RouteComponentProps> = (props) => {
Hier auch: navigate per destructure rausholen und später direkt einsetzen

2020-09-17 11:55 UTC, SmokyZone commented on app/pages/Packages/Packages.tsx
> +                window.confirm(
Ich habs an beiden Stellen entfernt. Was wäre da denn eine bessere möglichkeit, das zu machen?

2020-10-14 19:03 UTC, xyng requested changes
Ich hab' noch was zu meckern :-)

2020-10-14 19:03 UTC, xyng commented on app/pages/Packages/CreatePackage.tsx
> +const CreatePackage: React.FC<RouteComponentProps> = (props) => {
Gemeint war:
```ts
const CreatePackage: React.FC<RouteComponentProps> = ({ navigate }) => {
```

2020-10-14 19:03 UTC, xyng commented on app/pages/Packages/CreatePackage.tsx
> +    const { navigate } = props
Das dann entsprechend weg

2020-10-14 19:03 UTC, xyng commented on app/pages/Packages/CreatePackage.tsx
> +            if (props !== undefined && navigate !== undefined) {
Vorschlag (return early):

```ts
if (!props || !navigate) {
    return
}

await navigate(...) // await ist hier optional
```

2020-10-14 19:03 UTC, xyng commented on app/pages/Task/CreateTask.tsx
> +const CreateTask: React.FC<RouteComponentProps> = (props) => {
Siehe diese Konversation: https://github.com/xyng/yuoshi-studip-plugin/pull/19/files#r485187617

2021-10-21 13:50 UTC, closed without merging