Stationen
xyng/yuoshi-studip-plugin pull request #28
Opened 2021-02-05 16:26 UTC by juliandierker

2021-02-25 09:15 UTC, xyng requested changes
Insgesamt schon ganz gut. Ein paar Kleinigkeiten habe ich noch gefunden.
Weiterhin passt bei `getProgress` noch was nicht. In `Stations.php` ist es nicht korrekt angepasst und in `Package.php` müsste das streng genommen neu gebaut werden (ggf. aufbauend auf dem Progress der Stationen?)

2021-02-25 09:15 UTC, xyng commented on migrations/3_station_table_add.php
> +        // Nothing so far
Hier fehlt noch eine Down-Migration.
Dazu das Feld Package-ID wiederherstellen (zunächst nullable setzen), Update mit Inner-Join auf Stations machen, `tasks.package_id = stations.package_id` setzen und dann Package-ID nicht-nullbar machen.
Anschließend kannst du das station_id-Feld und die Stations-Tabelle entfernen.

2021-02-25 09:15 UTC, xyng commented on sql/yuoshi_initial_up.sql
> +CREATE TABLE IF NOT EXISTS `yuoshi_stations` (
Ich bin mir nicht sicher, ob das wirklich hier drin sein sollte. Die Tabelle wird doch eigentlich später durch die Migrations-Skripte angelegt?

2021-02-25 09:15 UTC, xyng commented on src/Api/Controller/PackagesController.php
> +
Whitespace bitte entfernen.

2021-02-25 09:15 UTC, xyng commented on src/Api/Controller/StationController.php
> +// use JsonApi\Routes\Packages\Authority as PackageAuthority;
Auskommentierten Code bitte entfernen

2021-02-25 09:15 UTC, xyng commented on src/Api/Controller/TasksController.php
> +            throw new \InvalidArgumentException("Cannot select Station without station filter.");
Es müsste heißen:
`Cannot select Tasks without station filter`

2021-02-25 09:15 UTC, xyng commented on src/Authority/StationAuthority.php
> +    // public static function findFiltered(array $ids, User $user, array $perms = [], array $conditions = []): array
Auskommentierten Code bitte entfernen

2021-02-25 09:15 UTC, xyng commented on src/Model/Packages.php
> +                        'yuoshi_packages.id' => new QueryField('TotalTasks.station_id')
Das Passt nicht. Du vergleichst hier die ID vom Package mit der Referenz auf die Station-ID vom Task.
GGf. möchtest du links `yuoshi_stations.id` schreiben?

2021-02-25 09:15 UTC, xyng commented on src/Model/Packages.php
> +                        'yuoshi_packages.id' => new QueryField('yuoshi_tasks.station_id')
Das Passt nicht. Du vergleichst hier die ID vom Package mit der Referenz auf die Station-ID vom Task.
GGf. möchtest du links `yuoshi_stations.id` schreiben?

2021-02-25 09:15 UTC, xyng commented on src/Model/Stations.php
> +    // TODO: check in db if this package is playable by user.
Wird `$playable` genutzt? Wenn ich mich recht entsinne, war das nur für Packages gedacht und sollte für Stations nicht notwendig sein.
(Kann mich hier aber irren)

2021-02-25 09:15 UTC, xyng commented on src/Model/Stations.php
> +                        'yuoshi_packages.id' => new QueryField('TotalTasks.package_id')
Das muss noch zu Stations angepasst werden. Die Tasks haben ja keine package_id mehr.

2021-02-25 09:15 UTC, xyng commented on src/Model/Stations.php
> +                        'yuoshi_packages.id' => new QueryField('yuoshi_tasks.station_id')
Das Passt nicht. Du vergleichst hier die ID vom Package mit der Referenz auf die Station-ID vom Task.
GGf. möchtest du links `yuoshi_stations.id` schreiben?

2021-02-25 09:15 UTC, xyng commented on src/Model/Packages.php
> +    public function getProgress(User $user, bool $byUsers = false)
GGf. prüfen, ob diese Methode weg muss oder anders gebaut werden muss.
Die gleiche Logik hast du im Station-Model auch gebaut.

2021-02-25 09:15 UTC, xyng commented on src/Model/Stations.php
> +                'yuoshi_packages.id',
```suggestion
                'yuoshi_stations.id',
```

2021-02-25 09:15 UTC, xyng commented on src/Model/Stations.php
> +                'yuoshi_packages.id'
```suggestion
                'yuoshi_stations.id'
```

2021-02-25 09:15 UTC, xyng commented on src/Model/Stations.php
> +                'yuoshi_packages.id' => $this->id,
```suggestion
                'yuoshi_stations.id' => $this->id,
```

2021-03-08 10:50 UTC, juliandierker commented on app/contexts/StationContext.tsx
> +// TODO check reloadTasks and compare to reloadStation
konnte weg

2021-03-08 10:58 UTC, juliandierker commented on app/pages/Tasks/Tasks.tsx
> +    const { station } = useCurrentStationContext()
Import Export habe ich umgestellt und das funktioniert auch. Das currentPackage brauche ich hier denke ich.

2021-03-08 10:59 UTC, juliandierker commented on migrations/3_station_table_add.php
> +        // Nothing so far
Wollen wir jemals zurück? :D wenn ja, mache ich das

2021-03-08 11:03 UTC, juliandierker commented on sql/yuoshi_initial_up.sql
> +CREATE TABLE IF NOT EXISTS `yuoshi_stations` (
ok entferne es hier

2021-03-08 11:12 UTC, juliandierker commented on src/Model/Stations.php
> +                        'yuoshi_packages.id' => new QueryField('yuoshi_tasks.station_id')
Können wir hier zusammen kurz drauf schauen?

2021-03-08 11:13 UTC, juliandierker commented on src/Model/Packages.php
> +    public function getProgress(User $user, bool $byUsers = false)
Wir wollen in zukunft progress für packages und stations

2021-03-22 17:36 UTC, juliandierker commented on src/Model/Stations.php
> +                        'yuoshi_packages.id' => new QueryField('yuoshi_tasks.station_id')
aber yuoshi_stations macht auf jeden fall mehr sinn dort
die richtigen metriken für den stationen-progress würde ich gerne in einen anderen PR auslagern.

2021-04-06 13:21 UTC, merged