Fix/create task changes
xyng/yuoshi-studip-plugin pull request #67
Opened 2021-07-06 07:53 UTC by SmokyZone

REQUIRES https://github.com/xyng/yuoshi-backend-adapter/pull/22

Bitte beide PRs checken. Es funktioniert zwar auf meinem PC, aber im umgang mit dem Adapter und dem Backend bin ich mir noch nicht so sicher.

2021-07-07 10:18 UTC, juliandierker commented on app/models/Task.ts
> +        // [TaskTypeName.CARD]: "Karteikarte",
Kann dann raus

2021-07-07 10:19 UTC, juliandierker commented on app/components/Form/Input.tsx
> +> = ({ label, name, type, checked, value, placeholder, ...props }) => {
Was macht der placeholder hier genau?

2021-07-07 10:21 UTC, juliandierker commented on app/components/Form/Input.tsx
> +                            ? placeholder
Was macht der placeholder genau?

2021-07-07 10:36 UTC, juliandierker requested changes
Lass uns die fragen noch klären

2021-07-07 10:44 UTC, SmokyZone commented on app/components/Form/Input.tsx
> +                            ? placeholder
ich musste einen der react typen nutzen (weil typescript und so) und da defaultValue schon belegt war musste ich einen anderen typen finden um manuell Werte in den Input als default reinzupacken. da war placeholder am nächsten

2021-07-13 07:22 UTC, juliandierker commented on app/components/Form/Input.tsx
> +                            ? placeholder
Ok könne wir das Input-Schema anpassen? Was wird an anderen Stellen verwendet?

2021-07-13 08:28 UTC, juliandierker approved these changes
LGTM

2021-07-13 08:28 UTC, merged